- $formkit: 'password'
  name: 'token'
  value: '$token'
  label: 'Token'
  help: '您的番组计划访问令牌'

- $cmp: 'FormKit'
  props:
    name: 'syncCollectionAndEpisodeFinish'
    value: "$syncCollectionAndEpisodeFinish == 'true'"
    type: 'checkbox'
    id: 'syncCollectionAndEpisodeFinish'
    label: '是否单向同步收藏和播放进度？'
  help: '有且仅有收藏条目和剧集完成是，会单向同步您的收藏和播放进度到番组计划，从伊卡洛斯到番组计划。'

- $cmp: 'FormKit'
  props:
    name: 'nsfwPrivate'
    value: "$nsfwPrivate == 'true'"
    type: 'checkbox'
    id: 'nsfwPrivate'
    label: 'NSFW类型的条目是否将操作私有？'

- $cmp: 'FormKit'
  props:
    name: 'enableProxy'
    value: "$enableProxy == 'true'"
    type: 'checkbox'
    id: 'enableProxy'
    label: '是否开启代理?'
  help: '是否开启网络代理，使得访问番组计划走代理。'

- $formkit: 'select'
  if: '$get(enableProxy).value'
  name: 'proxyType'
  value: '$proxyType'
  label: '选择代理类型'
  options:
    http: 'http'
    socks: 'socks'
  help: '网络代理的类型，即代理的协议。'

- $formkit: 'text'
  if: '$get(enableProxy).value'
  name: 'host'
  value: '$host'
  label: 'IP地址'
  placeholder: 'xxx.xxx.xxx.xxx'
  validation: 'required'
  help: '代理的服务IP地址'

- $formkit: 'text'
  if: '$get(enableProxy).value'
  name: 'port'
  value: '$port'
  label: '端口'
  help: '代理的服务端口'
  validation: 'required|number|between:1,65535'
